Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,29 +1,40 @@
 steps:
   - name: 'ubuntu'
     entrypoint: 'bash'
-    args: 
-      - '-c' 
-      - |
-         echo "Listing files under /workspace/falskapi:"
-         ls -R /workspace/flaskapi || echo "Directory not found"
+    args:
+    - '-c'
+    - |
+      echo "Listing contents of /workspace:"
+      ls -la /workspace  
+  - name: 'gcr.io/cloud-builders/docker'
+    args: ['build','-t', 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app', '.']
+
+# steps:
+#   - name: 'ubuntu'
+#     entrypoint: 'bash'
+#     args: 
+#       - '-c' 
+#       - |
+#          echo "Listing files under /workspace/falskapi:"
+#          ls -R /workspace/flaskapi || echo "Directory not found"
       
-  - name: 'gcr.io/cloud-builders/docker'
-    args: ['build', '-f', 'eshanmalyala/flaskapi/Dockerfile', '-t', 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app', '.']
+#   - name: 'gcr.io/cloud-builders/docker'
+#     args: ['build', '-f', 'eshanmalyala/flaskapi/Dockerfile', '-t', 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app', '.']
 
-  - name: 'gcr.io/cloud-builders/docker'
-    args: ['push', 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app']
+#   - name: 'gcr.io/cloud-builders/docker'
+#     args: ['push', 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app']
 
-  - name: 'gcr.io/cloud-builders/gcloud'
-    args: [
-      'run', 'deploy', 'flask-cloudbuild-app',
-      '--image', 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app',
-      '--region', 'us-central1',
-      '--platform', 'managed',
-      '--allow-unauthenticated'
-    ]
+#   - name: 'gcr.io/cloud-builders/gcloud'
+#     args: [
+#       'run', 'deploy', 'flask-cloudbuild-app',
+#       '--image', 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app',
+#       '--region', 'us-central1',
+#       '--platform', 'managed',
+#       '--allow-unauthenticated'
+#     ]
 
-images:
-  - 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app'
+# images:
+#   - 'us-central1-docker.pkg.dev/sharedproejcet-1/gae-standard/flask-cloudbuild-app'
 
 
-logsBucket: 'gs://mybucket579'
+# logsBucket: 'gs://mybucket579'
